title: Melrﾅ行e, programming your melodies
description: melrﾅ行e is a tool to create music by programming melodies and uses a custom language to composes notes that are played with MIDI. Note sequences in your program can be changed while playing which makes it possible to even use it for live performance. For the best experience, use the melrﾅ行e together with the Visual Studio Code Plugin for Melrﾅ行e.
theme: jekyll-theme-leap-day

show_downloads: true
google_analytics: UA-2987987-18